name: Hybrid Selenium and Playwright CI

on:
  workflow_dispatch:
    inputs:
      engine:
        description: 'Choose the engine to run the tests (selenium or playwright)'
        required: true
        default: 'selenium'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run Tests
      run: |
        pytest --engine=${{ github.event.inputs.engine }}
