name: Hybrid Selenium and Playwright CI

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Choose the job to run (run_selenium, run_playwright, run_tests)'
        required: true
        default: 'run_tests'

jobs:
  run_tests:
    if: ${{ github.event.inputs.job_name == 'run_tests' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [ selenium, playwright ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
      - name: Run ${{ matrix.job }} Tests
        run: |
          pytest --engine=${{ matrix.job }}

  run_selenium:
    if: ${{ github.event.inputs.job_name == 'run_selenium' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          pip install allure-pytest

      - name: Run Selenium Tests with Allure
        run: |
          pytest --engine=selenium --alluredir=./reports
        continue-on-error: true

      - name: Check if Allure Reports Exist
        run: |
          if [ ! -d "./reports" ]; then echo "Allure reports not generated"; exit 1; fi

      - name: Upload Allure Results as Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./reports

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.22.0.tgz
          tar -xzvf allure.tgz

      - name: Generate Allure Report
        if: success()
        run: ./allure-2.22.0/bin/allure generate ./reports --clean -o ./allure-report

      - name: Serve Allure Report
        if: success()
        run: ./allure-2.22.0/bin/allure open ./allure-report
  
  run_playwright:
    if: ${{ github.event.inputs.job_name == 'run_playwright' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
      - name: Run Playwright Tests
        run: |
          pytest --engine=playwright