name: Hybrid Selenium and Playwright CI

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Choose the job to run (run_selenium, run_playwright, run_tests)'
        required: true
        default: 'run_tests'

jobs:
  run_tests:
    if: ${{ github.event.inputs.job_name == 'run_tests' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [selenium, playwright]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run ${{ matrix.job }} Tests
      run: |
        pytest --engine=${{ matrix.job }}

  run_selenium:
    if: ${{ github.event.inputs.job_name == 'run_selenium' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run Selenium Tests
      run: |
        pytest --engine=selenium

  run_playwright:
    if: ${{ github.event.inputs.job_name == 'run_playwright' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run Playwright Tests
      run: |
        pytest --engine=playwright